;; Audio channels
%define SOUND_CHANNEL             0
%define MUSIC_CHANNEL             1
%define NB_WOLFASM_AUDIO_CHANNELS 2

;; Define sounds here
%define SOUND_PISTOL      0
%define SOUND_SHOTGUN     1
%define SOUND_BARREL      2
%define SOUND_NO_AMMO     3
%define NB_WOLFASM_SOUNDS 4

;; Define musics here
%define MUSIC_MENU_0            0
%define MUSIC_MENU_1            1
%define MUSIC_MENU_2            2
%define MUSIC_MENU_3            3
%define NB_WOLFASM_MUSIC_MENU   4
%define NB_WOLFASM_MUSICS       4
