;; Menu list
%define MENU_MAIN                     0
%define MENU_MULTIPLAYER              1
%define MENU_SELECT_MAP_SOLO          2
%define MENU_MULTIPLAYER_CONNECT      3
%define MENU_MULTIPLAYER_HOST         4
%define NB_MENUS                      5

;; MENU_MAIN buttons
%define BUTTON_PLAY                   0
%define BUTTON_MULTIPLAYER            1
%define BUTTON_EXIT                   2
%define NB_BUTTON_MAIN                3

;; MENU_MULTIPLAYER buttons
%define BUTTON_MP_HOST                0
%define BUTTON_MP_CONNECT             1
%define BUTTON_MP_BACK                2
%define NB_BUTTON_MULTIPLAYER         3

;; MENU_SELECT_MAP_SOLO buttons
%define BUTTON_SM_SOLO_MAP            0
%define BUTTON_SM_SOLO_BACK           1
%define NB_BUTTON_SELECT_MAP_SOLO     2

;; MENU_MULTIPLAYER_CONNECT buttons
%define BUTTON_MP_CO_CONNECT          0
%define BUTTON_MP_CO_BACK             1
%define NB_BUTTON_MULTIPLAYER_CONNECT 2

;; MENU_MULTIPLAYER_HOST buttons
%define BUTTON_MP_HOST_MAP            0
%define BUTTON_MP_HOST_BACK           1
%define NB_BUTTON_MULTIPLAYER_HOST    2
